[regfox]

# The name of the event as displayed on the badges.
event_name = "Event Name Here"

# RegFox API key. Get it from Extras->Integrations
# Don't check it into the repo.
api_key = "00000000000000000000000000000000"

# RegFox form number. Get it from the URL.
# https://manage.webconnex.com/a/<some number>/pages/<form id>
# You can also use this script to query available forms: regfox.py -c config.toml --show-forms
form_id = 1

# Date the event starts. (This date will be used to calculate attendee ages.)
start_date = "1955-09-12"

# SQLite database that will be used to store the cache.
# Using :memory: is acceptable with the following caveats:
#  * It will use more API calls if you restart the server.
#  * The --search-registrants and --get-registrants will use two API calls per 50 registrants.
database_file = ":memory:"

[printer]

# Default CUPS printer to use.
printer_name = "DYMO-LabelWriter-450"

# Default font to print badges with. (This can be overridden in the template.)
default_font = "LiberationSansNarrow-Regular.ttf"

# Pathname to the template to use to render the badge.
# Given filename ABC.py, the class name should be ABCTemplate
badge_template = "GenericBadge.py"

[frontend]

# Number of seconds between updates from RegFox.
# Each update will use two API requests per 50 new registrants. (Minimum of two.)
update_period = 60

# Uncomment this section for SSL support.
#[frontend.ssl]

# Set the filename that contains your SSL cert here. (If you have a combined cert, set this.)
#ssl_cert = "cert.pem"

# Set the filename that contains your SSL key here. (If you have a combined cert, omit this.)
#ssl_key = "key.pem"

# Set the passphrase for your SSL key here. (If it's unencrypted, omit this.)
#ssl_key_passphrase = "correct horse battery staple"
